version: '3.3'

services:
  webapp:
    build:
      context: .
      dockerfile: ./container/webapp/Dockerfile
    ports:
      - 8080:80

  database:
    build:
      context: .
      dockerfile: ./container/database/Dockerfile
    ports:
       - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: aubonbeurre

  unit:
    build:
      context: .
      dockerfile: ./container/unity/Dockerfile
    volumes:
      - ./src/script/:/opt/script/

  app_middleware:
    build:
      context: .
      dockerfile: ./container/middleware/Dockerfile
    volumes:
      - ./src/app_middleware/:/opt/aubonbeurre

